# Starter pipeline
- task: katalonTask@0
- task: katalonTask@0
  inputs:
    location: 'C:\Users\ieabelma\Downloads\Katalon_Studio_Windows_64-6.2.0 (1)\Katalon_Studio_Windows_64-6.2.0\katalon.exe'
  inputs:
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'



  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**'
      searchFolder: '$(System.DefaultWorkingDirectory)'
